-- MySQL Script generated by MySQL Workbench
-- Mon Mar 16 11:24:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aulasUsjt
-- -----------------------------------------------------
-- 
-- 
DROP SCHEMA IF EXISTS `aulasUsjt` ;

-- -----------------------------------------------------
-- Schema aulasUsjt
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aulasUsjt` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `aulasUsjt` ;

-- -----------------------------------------------------
-- Table `aulasUsjt`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aulasUsjt`.`Pais` ;

CREATE TABLE IF NOT EXISTS `aulasUsjt`.`Pais` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `populacao` BIGINT(20) NULL,
  `area` DECIMAL(15,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

